Add instrumentation of driver_requests_* metrics
gardener/machine-controller-manager-provider-aws pull request #153
Opened 2024-01-09 09:51 UTC by saley89

**What this PR does / why we need it**:
In version [v0.50.0](https://github.com/gardener/machine-controller-manager/releases/tag/v0.50.0) of MCM new metrics were added to record driver request durations and failures. It is for the provider's to implement the logic of updating these metrics at the appropriate points in the code base based on their driver activity with the provider.  

This PR is based on the [machine-controller-manager-provider-azure](https://github.com/gardener/machine-controller-manager-provider-azure/blob/d4b3b5d4d48cf3ea95bd7e39b334aeb3016e95d2/pkg/azure/instrument/instrument.go#L62-L82) implementation of these metrics and adds the duration of requests and records any failures during these operations:

* create machine
* delete machine
* list machines
* get machine status 
* get volume ids

**Which issue(s) this PR fixes**:
Fixes #152

**Special notes for your reviewer**:

See the linked `machine-controller-manager-provider-azure` project and whether we are able to take their `instrument.go` function as is.

**Release note**:
```feature user
Implements the driver metrics added to MCM in version `0.50.0` such that duration of calls to AWS and any failed requests are recorded:
* driver_request_duration_seconds
* driver_requests_failed_total
```

2024-01-26 14:01 UTC, rishabh-11 commented
Hey @saley89, with mcm v0.50 we also have introduced metrics for cloud provider API calls. I have raised an issue (https://github.com/gardener/machine-controller-manager-provider-aws/issues/156) for implementing these in provider-aws.  Would you like to implement these metrics as a part of this PR or wait for the MCM team to implement it when we pick it up?

2024-01-26 16:42 UTC, saley89 commented
Hi @rishabh-11 my team has a need for the metrics that are implemented by this change and I noticed it was relatively straight forward to add these in based on the implementation in the other provider.  

If you are comfortable for this PR to go in for these metrics without the others that would be beneficial for us.  The other metrics could go in as and when you have time/are able to do so.

2024-01-27 12:17 UTC, rishabh-11 requested changes
Can you move the `instrument.go` file in a separate directory called `instrument` inside `pkg`?

2024-02-01 08:59 UTC, saley89 commented
@rishabh-11 sure, that is done now.

2024-02-05 12:46 UTC, rishabh-11 requested changes
just a minor change. rest is good. Also did you test this? Are the metrics working as expected?

2024-02-05 12:46 UTC, rishabh-11 commented on pkg/instrument/instrument.go
> +	// compute the time taken to complete the AZ service call and record it as a metric
```suggestion
	// compute the time taken to complete the AWS service call and record it as a metric
```

2024-02-08 16:11 UTC, saley89 commented
Regarding tests I think it can be done.  Looks like the way to go about it would be to leverage the testutils package of the client_go/prometheus package we already have in this repo.  Some of example of using it are in the [prometheus repo](https://github.com/prometheus/client_golang/blob/main/prometheus/testutil/testutil_test.go).

I had a brief look this afternoon to see if we can introduce it to the existing `core_test.go` tests but would need more time to get something ready for the PR.  In the meantime anyone can contribute to it if they have a solution. 

My thinking would be ideally to get the metric, call methods like `CreateMachine`, `DeleteMachine` and see that the metric with the relevant labels has indeed been incremented. Unfortunately the Azure example hasn't tested it either for reference.

2024-02-20 09:39 UTC, rishabh-11 commented
Hey @saley89, While testing your PR I found a bug in the code related to metrics. Can you refer to https://github.com/gardener/machine-controller-manager-provider-azure/pull/130 and fix this PR?

2024-02-22 09:53 UTC, rishabh-11 commented
/ping @saley89

2024-02-22 10:56 UTC, saley89 commented
@rishabh-11 I was able to pull in the changes needed for the updated driver API function. I needed to revendor due to go mod changes to bring in the latest prometheus golang client.  

I will rebase with master to fix these conflicts.

2024-02-22 11:02 UTC, saley89 commented
The rebase has got things back in order and this is now ready for your review again. Thanks

2024-02-22 15:05 UTC, unmarshall requested changes

2024-02-27 08:53 UTC, saley89 commented on pkg/aws/core.go
> +	defer instrument.DriverAPIMetricRecorderFn(createMachineOperationLabel, &err)
Fixed

2024-03-04 06:06 UTC, rishabh-11 approved these changes
/lgtm

2024-03-04 06:08 UTC, unmarshall approved these changes
/lgtm

2024-03-04 06:09 UTC, merged