[ci:component:github.com/gardener/machine-controller-manager:v0.52.0->v0.53.0]
gardener/machine-controller-manager-provider-aws pull request #162
Opened 2024-04-19 12:26 UTC by gardener-robot-ci-2

**Release Notes**:
```other operator github.com/gardener/machine-controller-manager #907 @rishabh-11
Updated k8s dependencies to `v0.29.3`
```
```other operator github.com/gardener/machine-controller-manager #903 @rishabh-11
Removed vendor directory
```
```breaking developer github.com/gardener/machine-controller-manager #898 @elankath
 New provider method Driver.InitializeMachine added for Post-Creation VM Instance Initialization steps.
```

2024-04-23 06:59 UTC, elankath commented
This is WIP and in testing at the moment and will also incorporate https://github.com/gardener/machine-controller-manager-provider-aws/pull/128

2024-05-07 07:06 UTC, axel7born commented
/lgtm

I checked that `Ipv6AddressCount` and `Ipv6PrefixCount` were added and an IPv6 address and an IPv6 prefix were assigned to the instance. To configure the machine class I have used https://github.com/gardener/gardener-extension-provider-aws/pull/785 of the aws provider and the shoot has been setup with `infrastructureConfig.dualStack.enabled=true`.

2024-05-17 04:34 UTC, rishabh-11 approved these changes
/lgtm

2024-05-17 04:47 UTC, rishabh-11 requested changes
minor change needed. Rest looks good.

2024-05-17 04:47 UTC, rishabh-11 commented on pkg/aws/core.go
>  	if providerSpec.SrcAndDstChecksEnabled != nil && !*providerSpec.SrcAndDstChecksEnabled {
```suggestion
	if providerSpec.SrcAndDstChecksEnabled != nil && !*providerSpec.SrcAndDstChecksEnabled && *requiredInstance.SourceDestCheck {
```
No need to call `disableSrcAndDestCheck` if it is already disabled.

2024-05-17 05:41 UTC, rishabh-11 approved these changes
/lgtm

2024-05-17 06:08 UTC, merged