Reintroduces support for multi volume support for EC2 instances
gardener/machine-controller-manager-provider-aws pull request #21
Opened 2021-02-02 10:49 UTC by prashanth26

**What this PR does / why we need it**:
This PR re-introduces the support for multi volume support for EC2 instances that is present in the in-tree version of MCM. Refer - https://github.com/gardener/machine-controller-manager/pull/397.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```noteworthy user
Fixes regressions while supporting multiple volumes support for EC2 instances
```
```noteworthy user
Adds support for gp3 volume types
```

2021-02-02 10:50 UTC, prashanth26 commented
/invite @AxiomSamarth @amshuman-kr

2021-02-02 10:54 UTC, prashanth26 commented
/priority blocker

2021-02-02 10:59 UTC, ialidzhikov commented
Wrt to the release note `Adds support for gp3 volume types` - I don't think that this PR adds any support for gp3. It is already there with aws-sdk-go that is up-to-date and allows creating gp3 volumes. IMO you can rework/remove this release note.

2021-02-02 11:32 UTC, prashanth26 commented
> Wrt to the release note Adds support for gp3 volume types - I don't think that this PR adds any support for gp3. It is already there with aws-sdk-go that is up-to-date and allows creating gp3 volumes. IMO you can rework/remove this release note.

Sure @ialidzhikov. Makes sense will remove it.

2021-02-02 11:56 UTC, prashanth26 commented
Just ran this against changes against a (shoot) cluster and was able to create machines with multiple disks (even of type `gp3`)

2021-02-02 16:24 UTC, amshuman-kr requested changes
Overall LGTM. Some minor nits.

2021-02-02 16:24 UTC, amshuman-kr commented on pkg/aws/apis/validation/validation.go
> +			allErrs = append(allErrs, field.Required(idxPath.Child("ebs.volumeType"), "Please mention a valid EBS volume type: gp2, gp3, io1, st1, sc1, or standard"))
```suggestion
			allErrs = append(allErrs, field.Required(idxPath.Child("ebs.volumeType"), fmt.Sprintf("Please mention a valid EBS volume type: %v", validVolumeTypes)))
```

2021-02-02 16:24 UTC, amshuman-kr commented on pkg/aws/apis/validation/validation.go
> +		if disk.Ebs.VolumeType == "io1" && disk.Ebs.Iops <= 0 {
Might be better to move `io1` as a constant [here](https://github.com/gardener/machine-controller-manager-provider-aws/blob/master/pkg/aws/apis/aws_provider_spec.go)

2021-02-02 16:24 UTC, amshuman-kr commented on pkg/aws/apis/validation/validation.go
> +		allErrs = append(allErrs, field.Required(fldPath, "Device name with '/root' partition must be specified"))
```suggestion
		allErrs = append(allErrs, field.Required(fldPath, "One device must be specified as root"))
```

2021-02-02 16:24 UTC, amshuman-kr commented on pkg/aws/apis/validation/validation.go
> +		allErrs = append(allErrs, field.Required(fldPath, "Only one '/root' partition can be specified"))
```suggestion
		allErrs = append(allErrs, field.Required(fldPath, "Only one device can be specified as root"))
```

2021-02-02 16:24 UTC, amshuman-kr commented on pkg/aws/apis/validation/validation_test.go
> +							Detail:   "Please mention a valid EBS volume type: gp2, gp3, io1, st1, sc1, or standard",
```suggestion
							Detail:   fmt.Sprintf("Please mention a valid EBS volume type: %v", validVolumeTypes),
```

2021-02-02 16:24 UTC, amshuman-kr commented on pkg/aws/apis/validation/validation_test.go
> +			Entry("NI are missing", &data{
```suggestion
			Entry("NICs are missing", &data{
```

2021-02-02 18:16 UTC, prashanth26 commented
Hi @amshuman-kr ,

I have tried to address your comments with this commit - https://github.com/gardener/machine-controller-manager-provider-aws/pull/21/commits/35174d5e967deee3cd2832cf1ff8f9ea85009ba3. I prehaps got lazy while copying code over. Thanks for making me do the right thing 👍

2021-02-02 20:14 UTC, ialidzhikov commented
> > Wrt to the release note Adds support for gp3 volume types - I don't think that this PR adds any support for gp3. It is already there with aws-sdk-go that is up-to-date and allows creating gp3 volumes. IMO you can rework/remove this release note.
> 
> Sure @ialidzhikov. Makes sense, reworked it.

The current release note `Updated validations to allow provisioning of `gp3` volume types attached to EC2 instances` is not appropriate. Currently there is no validation that prevents provisioning instances with `gp3`. Please change the release note to something similar to `Validation for block devices is now improved`.

2021-02-02 22:31 UTC, prashanth26 commented
> > > Wrt to the release note Adds support for gp3 volume types - I don't think that this PR adds any support for gp3. It is already there with aws-sdk-go that is up-to-date and allows creating gp3 volumes. IMO you can rework/remove this release note.
> > 
> > 
> > Sure @ialidzhikov. Makes sense, reworked it.
> 
> The current release note `Updated validations to allow provisioning of gp3 volume types attached to EC2 instances` is not appropriate. Currently, there is no validation that prevents provisioning instances with `gp3`. Please change the release note to something similar to `Validation for block devices is now improved`.

Okay 👌 . Done.

2021-02-02 22:58 UTC, prashanth26 commented
I have squashed all the changes

Merging now.

2021-02-02 22:59 UTC, merged

2021-02-03 05:35 UTC, amshuman-kr commented
/lgtm