Adds Golang based IT for provider AWS
gardener/machine-controller-manager-provider-aws pull request #42
Opened 2021-08-31 16:28 UTC by himanshu-kun

**What this PR does / why we need it**:
This PR adds integration test for aws mcm controllers.

**Which issue(s) this PR fixes**:
Fixes #40 

**Special notes for your reviewer**:
The tests uses common framework from `machine-controller-manager` repository.
**Release note**:

```feature developer
A new integration test using Ginkgo Framework for aws machines creation and deletion has been added
```

2021-08-31 16:51 UTC, AxiomSamarth requested changes
Haven't reviewed the vendored files from MCM Integration test Suite. As anyway it will be vendored freshly after the next release. I will have the changes in Suite reviewed over there. Here are some other local nits.

2021-08-31 16:51 UTC, AxiomSamarth commented on go.mod
> +	github.com/gardener/machine-controller-manager => github.com/rkjakeer/machine-controller-manager v0.38.1-0.20210708085258-8fd87c692191
Leaving a comment, so that we remember to update the go.mod file with proper vendoring.

2021-08-31 16:51 UTC, AxiomSamarth commented on test/integration/provider/rti.go
> +	integrationTestTagValue := "1"
Make them global variables as they are used in both `InitializeResourcesTracker` and `probeResources`

2021-09-06 09:55 UTC, AxiomSamarth reviewed
A very minor nit. Everything else looks good to me.

2021-09-06 09:55 UTC, AxiomSamarth commented on test/integration/provider/aws.go
> +func getOrphanedVMs(tagName string, tagValue string, machineClass *v1alpha1.MachineClass, secretData map[string][]byte) ([]string, error) {
You can name it as `getOrphanesInstances` as `Instances` is the term AWS uses. Also, match the function name in the comment.

2021-09-13 07:35 UTC, AxiomSamarth commented
@himanshu-kun - This reference [PR](https://github.com/gardener/machine-controller-manager/pull/632/files) should fix the build error.

2021-09-13 07:38 UTC, himanshu-kun commented
Thanks @AxiomSamarth !

2021-09-13 10:24 UTC, merged