Handle Eventual Consistency Problem in Create Driver Call
gardener/machine-controller-manager-provider-aws pull request #58
Opened 2021-12-22 12:24 UTC by himanshu-kun

**What this PR does / why we need it**:
This PR takes care of problem where due to eventual consistency problem of AWS multiple instances get created
**Which issue(s) this PR fixes**:
Fixes #54 

**Special notes for your reviewer**:
I have made `maxElapsedTimeInBackoff` as a variable and not a `const` because I change this for the unit tests so that for unit-tests the retrying interval is 10sec and not 5min.
**Release note**:

```bugfix user
A problem is resolved where multiple VMs were created by the driver in case the APIs on the AWS are not consistent for some time.
```

2021-12-22 14:21 UTC, AxiomSamarth reviewed
/lgtm

2021-12-22 14:21 UTC, AxiomSamarth commented
/invite @dkistner @kon-angelo

2021-12-22 14:22 UTC, AxiomSamarth requested changes

2021-12-22 14:22 UTC, AxiomSamarth commented on pkg/aws/core_util.go
> +func confirmInstanceById(svc ec2iface.EC2API, instanceID string) (bool,error){
```suggestion
func confirmInstanceByID(svc ec2iface.EC2API, instanceID string) (bool,error){
```

2022-01-03 13:07 UTC, kon-angelo approved these changes
/lgtm

2022-01-21 07:49 UTC, dkistner approved these changes
/lgtm

2022-01-21 08:50 UTC, merged