orphan collection of NIC during Integration Tests
gardener/machine-controller-manager-provider-aws pull request #84
Opened 2022-05-24 09:07 UTC by Mkmittal

**What this PR does / why we need it**:
Adds orphan Collection of NIC during Integration tests using tags.
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
NONE
```

2022-05-24 09:44 UTC, himanshu-kun approved these changes
/lgtm

2022-05-24 09:44 UTC, himanshu-kun commented on test/integration/provider/rti.go
> +	//clusterTagValue := "1"
remove it if its not used now

2022-05-24 09:44 UTC, himanshu-kun commented on test/integration/provider/aws.go
> +	inputNI := &ec2.DescribeNetworkInterfacesInput{
inputNI -> inputNIC

2022-05-24 09:44 UTC, himanshu-kun requested changes
kindly address the comments otherwise lg

2022-05-24 10:39 UTC, Mkmittal commented on test/integration/provider/aws.go
> +	inputNI := &ec2.DescribeNetworkInterfacesInput{
ok
Done

2022-05-24 10:39 UTC, Mkmittal commented on test/integration/provider/rti.go
> +	//clusterTagValue := "1"
Done

2022-05-25 04:54 UTC, Mkmittal commented
@himanshu-kun, the requested changes have been made.

2022-05-25 09:11 UTC, himanshu-kun approved these changes
/lgtm

2022-05-25 10:58 UTC, merged